#!/bin/bash

running=`ps -ef | grep clientdisplay.pyc | grep /usr/bin | grep $USER`
if [ -n "$running" ]; then
	echo "is running"
	exit
fi

app_command='/usr/bin/python /usr/bin/clientdisplay.pyc $@'

${app_command}

# if [ `id -u` -eq 0 ]; then
# 	#user is admin
# 	${app_command}
# else
# 	#user is not admin
# 	if `echo $- | grep "i" >/dev/null 2>&1`; then
# 		#script is running in interactive mode
# 		su - -c " LD_LIBRARY_PATH=/usr/lib/registerclient ${app_command}"
# 	else
# 		#script is running in non-interactive mode
# 		if command -v pkexec >/dev/null 2>&1; then
# 			pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY LD_LIBRARY_PATH=/usr/lib/registerclient ${app_command}
# 		elif command -v gksu >/dev/null 2>&1; then
# 			gksu LD_LIBRARY_PATH=/usr/lib/registerclient ${app_command}
# 		elif command -v sudo >/dev/null 2>&1; then
# 			x-terminal-emulator -e "sudo  LD_LIBRARY_PATH=/usr/lib/registerclient ${app_command}"
# 		elif command -v su >/dev/null 2>&1; then
# 			x-terminal-emulator -e "su - -c ' LD_LIBRARY_PATH=/usr/lib/registerclient ${app_command}'"
# 		else
# 			x-terminal-emulator -e "echo 'Command must be run as root user: ${app_command}'"
# 		fi
# 	fi
# fi
